### PR TITLE
Added robblog to the distribution to start testing on jenkins.

### PR DESCRIPTION
**Pull request by hawesie**
This will fail initially because rosdeps are missing, but these have been requested: https://github.com/ros/rosdistro/pull/5692

### CODE REVIEW

**Comment by marc-hanheide** [comment]
you could add those to our own [rosdep](https://github.com/strands-project/rosdistro/tree/strands-devel/rosdep) for a start... but it wouldn't help much as one would have to manually add this to `/etc/ros/rosdep/sources.list.d`

**Comment by marc-hanheide** [comment]
I'll wait for the rosdep pull request to be accepted then.

**Comment by marc-hanheide** [comment]
BTW... we have the same Travis checks ;-)

**Comment by hawesie** [comment]
Good to go.

**Comment by marc-hanheide** [comment]
I already corrected the format... trailing spaces hat shouldn't be there... let's see if it passes now

**Comment by marc-hanheide** [comment]
passed the test now, build triggered on jenkins

**Comment by marc-hanheide** [comment]
actually that was leading spaces...

**Comment by marc-hanheide** [comment]
failed: http://lcas.lincoln.ac.uk/jenkins/job/devel-hydro-robblog/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=devel/1/

`apt-get install jekyll` doesn't work... no idea why `gem` is resolved with `apt`... You @hawesie ?

**Comment by hawesie** [comment]
No, no idea. If I run `rosdep install robblog` locally it correctly runs `sudo gem install jekyll`.

**Comment by marc-hanheide** [comment]
well... seems they didn't implement that correctly in their jenkins scripts :-( I'll investigate.

**Comment by hawesie** [comment]
This is a low priority package though, but so no rush.

**Pull request merged**
