### PR TITLE
mongodb_store: 0.3.1-0 in 'indigo/distribution.yaml' [bloom]

### PR DESCRIPTION
**Pull request by hawesie**
Increasing version of package(s) in repository `mongodb_store` to `0.3.1-0`:

- upstream repository: https://github.com/strands-project/mongodb_store.git
- release repository: https://github.com/strands-project-releases/mongodb_store.git
- distro file: `indigo/distribution.yaml`
- bloom version: `0.5.26`
- previous version for package: `0.1.30-0`

## libmongocxx_ros

- No changes

## mongodb_log

- No changes

## mongodb_store

```
* remove mongoclient libs from CMakeLists
* Contributors: Bruno Lacerda
```

## mongodb_store_msgs

- No changes

### CODE REVIEW

**Comment by hawesie** [comment]
This is the release as discussed here: https://github.com/strands-project/mongodb_store/pull/194#issuecomment-320202627

**Comment by hawesie** [comment]
This changes to kinetic-devel as the release branch.

**Comment by hawesie** [comment]
@marc-hanheide I really don't see where this error comes from.

**Comment by marc-hanheide** [comment]
test this please

**Comment by marc-hanheide** [comment]
there was a conflict upstream

**Pull request merged**
