### PR TITLE
Added strands_tabletop_perception

### PR DESCRIPTION
**Pull request by hawesie**

### CODE REVIEW

**Comment by hawesie** [comment]
Can we only build public repos or is it just that this test only passes with public repos?

```
ERROR: In file '''/home/travis/build/strands-project/rosdistro/indigo/distribution.yaml''': Could not validate source entry for repo strands_tabletop_perception with error [[[Could not validate repository with url https://github.com/strands-project/strands_tabletop_perception.git and version hydro-devel from entry at line '''8875''']]]
```

**Comment by marc-hanheide** [comment]
we can only build public repos, yes.

**Comment by marc-hanheide** [comment]
let's put it that way, I have never tried private ones. It _might_ work for devel builds... but then you are to some extend exposing some of you stuff through jenkins (it's not hardened to keep the source code secret)

**Comment by marc-hanheide** [comment]
you can try to merge this, but no guarantees

**Comment by hawesie** [comment]
@cburbridge @mzillich can we make strands_tabletop_perception public, or should it remain private for now?

**Comment by marc-hanheide** [comment]
Just try to merge. It won't destroy anything

**Comment by marc-hanheide** [comment]
Releasing might also work bit then it is effectively open source

**Comment by mzillich** [comment]
For now I would prefer to keep it private. Is that a problem?

**Comment by hawesie** [comment]
No, that's fine. I think we should aim to release most stable things after the deployment though,

**Comment by mzillich** [comment]
Ok, cool. We will soon reorganise our stuff to separate the free from the non-free parts, so that this whole process becomes more straight forward.

**Pull request closed without merging**
