### PR TITLE
Removed robblog and added executive

### PR DESCRIPTION
**Pull request by hawesie**
Added executive just to see what happens ;)

### CODE REVIEW

**Comment by marc-hanheide** [comment]
The name of this pull request is misleading... It was your intention to remove robblog but _ADD_ strands_executive, right?

**Comment by hawesie** [comment]
Yup.

**Comment by marc-hanheide** [comment]
Another observation/problem:

In order to figure out what _our_ repositories are in the big universe of ros packages to be found in `distribution.yaml` I apply a filter on the URL, namely `http://github.com/strands-project/*`. That means only for repositories in `distribution.yaml` that have a source URL starting with this, devel jobs are created. Your PR sets it to `http://github.com/hawesie`, so it's filtered out. I could change it so it also accepts repositories under `http://github.com/hawesie` or you move it to ``http://github.com/strands-project`

**Comment by hawesie** [comment]
I'm happy to move it.

**Pull request merged**
