### PR TITLE
Adding theano and deepfried2

### PR DESCRIPTION
**Pull request by Pandoro**
Is the naming okay?

### CODE REVIEW

**Comment by marc-hanheide** [comment]
Check this:

```
ERR: list out of alphabetical order line 35.  'deepfried2' should come before 'strands-twython'
```

the keys need to be in alphabetically order...

**Comment by marc-hanheide** [comment]
Naming is fine though

**Comment by marc-hanheide** [comment]
Sorry, there's another glitch in there:

```
deepfried2:
  ubunut: [python-deepfried2_0.01_all]
theano:
  ubunut: [python-theano_0.8.0rc1_all]
```

I guess it should be `ubuntu` instead of `ubunut`

**Comment by marc-hanheide** [comment]
Oh, and the packages should be named:

```
python-theano
python-deepfried2
```

without the version information

**Comment by Pandoro** [comment]
Wow, today is really not my day. I just changed it, but now I'm not even sure if I did what you meant. Did I change the package name correctly, or should I have left the names as they were and just remove the versions from them?

**Comment by marc-hanheide** [comment]
Aarg... you got me wrong, the ubuntu packages need to be called differently. I don't care what you name the keys, so
`python-deepfried2` instead of `python-deepfried2_0.01_all` and `python-theano` instead of `python-theano_0.8.0rc1_all`

**Comment by marc-hanheide** [comment]
You got it :-P

**Comment by Pandoro** [comment]
The embarrassment, I'm almost certain that there will still be something that is wrong.  T_T

**Comment by marc-hanheide** [comment]
yeah!!! you have earned whatever your vegan treat will be tonight.

**Comment by Pandoro** [comment]
Woohooo :D Food! I choose food!

**Pull request merged**
